### ISSUE TITLE
使用 Sass 编写 CSS Variables

### ISSUE THREAD

**Issue by ch1oechao** [ch1oechao/code#12]
Sass 是一款 CSS  预处理器，它被许多开发者接受的主要原因在于提供了许多可编程的语法去编写 CSS，比如自定义变量、嵌套、Mixin、Function 等等。而 CSS4 目前也推出了新语法 CSS Variables 支持自定义变量。

## Sass 与 CSS Variables 编写变量的区别
Sass 编写变量

```sass
$color-white-1: #FFF;

.container {
  background-color: $color-white-1;
}
```

CSS Variables 编写变量

```css
:root {
  --color-white-1: #FFF;
}

.container {
  background-color: var(--color-white-1);
}
```

两种方式最终都可以让容器的背景色为白色，但对于开发角度来说，原生的 CSS Variables 的优势会更明显。

- 不需要预处理，它本身就被浏览器所认可，而 Sass 需要编译成为 CSS 才能被使用。
- 拥有层叠样式的特点，支持局部变量覆盖。
- 更好的支持主题更换，因为随着变量值的改变，浏览器也会同时进行页面重绘。
- 可以由 JavaScript 获取到，并进行修改操作。

局部覆盖可以在 `.container` 里重新定义 `--color-blue-1`  的值，那么最终容器展现的颜色为 `.container` 里定义的变量值，而不是 `:root` ，因为局部变量做了覆盖。

```css
:root {
  --color-blue-1: #78A9FF;
}
.container {
  --color-blue-1: #99DDFF;
  background-color: var(--color-blue-1);
}
```

而使用 Sass 编写变量也是大多数开发者的选择，因为当前浏览器的兼容程度不一，网站最终依赖的样式脚本应该更具有兼容性。

- 通过 Webapck、PostCSS 等组合工具将 Sass 编译成普通的样式，就可以不用担心样式兼容性问题。
- Sass 还提供了多种可编程语法：@mixin、@function、@import 让编写样式更方便。

## 如何将 Sass 与 CSS Variables 一起工作

怎么巧妙的将两者结合在一起写样式呢，我们可以借助 Sass 提供的多样函数语法，去完成 CSS Variables 的定义。

### 借助 Sass Maps 定义 CSS Variables

```sass
$colors: (
  white-1: #FFF,
  black-1: #000,
);
$sizes: (
  radius-md: 12px,
  font-md: 14px,
);
```

遍历 Sass Maps

```sass
:root {
  @each $name, $color in $colors {
    --color-#{$name}: #{$color};
  }
  @each $name, $size in $sizes {
    --size-#{$name}: #{$size};
  }
}
```

编译后的结果为：

```css
:root {
  --color-white-1: #FFF;
  --color-black-1: #000;
  --size-radius-md: 12px;
  --size-font-md: 14px;
}
```

### 借助 Sass Function 使用 CSS Variables

```sass
@function --color($color-name) {
  @return var(--color-#{$color-name});
}
@function --size($size-name) {
  @return var(--size-#{$size-name});
}

.container {
  color: --color(white-1);
  background-color: --color(black-1);
  border-radius: --size(radius-md);
  font-size: --size(font-md);
}
```

编译后的结果为：

```css
.container {
  color: var(--color-white-1);
  background-color: var(--color-black-1);
  border-radius: var(--size-radius-md);
  font-size: var(--size-font-md);
}
```

最终的实现效果可以查看 [Codepen](https://codepen.io/zchen9/pen/VxPJbY)

### 两种变量计算方法

使用 Sass 中的  `#{}` 辅助编译成浏览器可识别的 CSS，最终用 CSS 的 `calc` 计算函数处理。

```scss
$size (
  interval-md: 8px;
);
// ...
$fixed-block-width: 300px;
.container {
  margin-left: calc(#{$fixed-block-width} + #{--size(interval-md)});
}
```

### 判断浏览器是否支持

- 通过 CSS support 判断

```css
@supports (display: var(--)) {
  // do something with CSS Variables
  :root {
    --color-pink-1: #FF99AA;
  }
}
```

具体例子可查看 Codepen [Supports CSS Variables](https://codepen.io/ire/pen/rdmboK))

- 通过 JavaScript 判断

```js
// 判断是否支持 window.CSS.supports
const isSupported = window.CSS && window.CSS.supports &&  window.CSS.supports('--a', 0);
// 在不支持的情况下，加载兼容版 CSS
if(!isSupported){
  removeCss('css-custom-properties.css');
  loadCss('without-css-custom-properties.css');
}
```

### 主题更换

利用 CSS Variables 局部变量的属性，可以快速的切换主题

- 在容器选择器下，编写不同主题的 CSS Variables，以下示例代码创建了 `theme-pink` 与 `theme-green` 两款颜色主题。

```css
.main-container {
  --color-brand-1: #78A9FF;
  --color-brand-2: #80C3FF;
  &.theme-pink {
    --color-brand-1: #FF3377;
    --color-brand-2: #FF6680;
  }
  &.theme-green {
    --color-brand-1: #15D1D1;
    --color-brand-2: #45E6CB;
  }
}
```

- 使用 JavaScript 通过切换容器的主题 `classname` 快速更改主题，以下示例代码简单地描述容器的主题 `classname` 切换。

```js
setTheme(name) {
  const $themeContainer = $('.main-container');
  const themeName = `theme-${name}`;
  const themeExp = new RegExp('^theme-\w?\s?', 'ig');
  const className = $themeContainer.attr('class') || '';
  const newClassName = className.split(' ').filter(n => !themeExp.test(n));
  $themeContainer.attr('class', `${themeName} ${newClassName.join(' ')}`);
}
```

- - - -

END.
